#!/bin/bash
# Fan out N concurrent agent.py rollouts across agents 0..N-1.
#
# Each rollout retargets via HOMUNCULUS_PORT=2557<N> + MC_PLAYER_NAME=agent<N>,
# so craft.config wires the whole stack (homunculus HTTP base + console TPs)
# to the right client. JSONL default already auto-suffixes by player name.
#
# Usage:
#   scripts/concurrent_rollouts.sh                    # N=5, model=claude-haiku-4-5, default args
#   N=3 scripts/concurrent_rollouts.sh
#   MODEL=claude-haiku-4-5 TURNS=50 GOAL=survive_shelter scripts/concurrent_rollouts.sh
#
# Tails: logs go to results/rollout-<player>-<ts>.log; JSONL to
# results/rollout-<goal>-<ts>-agent<N>.jsonl (auto-generated by craft.agent).
#
# IMPORTANT: prereq is N PrismLauncher instances already running (use
# launch_agent.sh N) — this script does not boot clients, it only drives them.

set -uo pipefail

N="${N:-5}"
MODEL="${MODEL:-claude-haiku-4-5}"
TURNS="${TURNS:-50}"
GOAL="${GOAL:-survive_shelter}"
SPAWN_RANGE="${SPAWN_RANGE:-20000}"
PHASE="${PHASE:-dawn}"
PERMADEATH_FLAG="${PERMADEATH_FLAG:---permadeath}"
RESULTS_DIR="${RESULTS_DIR:-results}"
WORLD_WAIT_S="${WORLD_WAIT_S:-90}"  # max seconds to wait for each player to be in-world

case "$N" in
  [1-9]|10) ;;
  *) echo "N must be 1..10, got '$N'" >&2; exit 2 ;;
esac

cd "$(dirname "$0")/.."
mkdir -p "$RESULTS_DIR"

# Poll /stats until health is a positive number, indicating the player has
# joined the MC server. Exits 0 on success, 1 on timeout.
_wait_for_in_world() {
  local port="$1" player="$2" deadline="$3"
  local base="http://127.0.0.1:${port}"
  while true; do
    local health
    health=$(curl -sf --max-time 2 "${base}/stats" 2>/dev/null \
      | python3 -c "import sys,json; d=json.load(sys.stdin); h=d.get('health'); print(h if h else '')" \
      2>/dev/null || true)
    if [[ -n "$health" && "$health" != "None" && "$health" != "null" ]]; then
      echo "[concurrent_rollouts] ${player} in-world (HP=${health})"
      return 0
    fi
    if [[ $(date +%s) -ge $deadline ]]; then
      echo "[concurrent_rollouts] WARNING: ${player} not in-world after ${WORLD_WAIT_S}s — launching anyway"
      return 1
    fi
    sleep 2
  done
}

TS=$(date +%Y%m%d-%H%M%S)
echo "[concurrent_rollouts] N=$N model=$MODEL turns=$TURNS goal=$GOAL spawn=$SPAWN_RANGE phase=$PHASE ts=$TS"
echo "[concurrent_rollouts] waiting up to ${WORLD_WAIT_S}s per agent for in-world readiness..."

pids=()
for ((i=0; i<N; i++)); do
  port=$((25570 + i))
  player="agent${i}"
  log="${RESULTS_DIR}/rollout-${player}-${TS}.log"
  deadline=$(( $(date +%s) + WORLD_WAIT_S ))
  _wait_for_in_world "$port" "$player" "$deadline"
  echo "[concurrent_rollouts] launching ${player} port=${port} -> ${log}"
  HOMUNCULUS_PORT="$port" MC_PLAYER_NAME="$player" \
    uv run python -m craft.agent "$TURNS" "$GOAL" \
      --start-phase "$PHASE" \
      --random-spawn-range "$SPAWN_RANGE" \
      $PERMADEATH_FLAG \
      --model "$MODEL" \
      > "$log" 2>&1 &
  pids+=("$!")
  # Stagger startup by 2s so random_spawn TPs + difficulty sets don't slam
  # the server console all at the same instant.
  sleep 2
done

echo "[concurrent_rollouts] all ${N} agents launched; pids: ${pids[*]}"
echo "[concurrent_rollouts] tail logs: tail -f ${RESULTS_DIR}/rollout-agent*-${TS}.log"
echo "[concurrent_rollouts] waiting for completion..."

exit_codes=()
for pid in "${pids[@]}"; do
  wait "$pid"
  exit_codes+=("$?")
done

echo "[concurrent_rollouts] done. exit codes: ${exit_codes[*]}"
echo "[concurrent_rollouts] JSONLs: ls ${RESULTS_DIR}/rollout-${GOAL}-${TS:0:8}-*agent*.jsonl"
